#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Deep Learning for Breast Cancer Detection                                           #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config.yml                                                                         #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/BreastCancerDetection                              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 21st 2023 07:46:07 pm                                              #
# Modified   : Saturday December 30th 2023 03:22:12 pm                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
data:
  directories:
    base: data/
    images:
      raw: data/image/0_raw/CBIS-DDSM/

  meta:
    urls:
      calc_train: https://wiki.cancerimagingarchive.net/download/attachments/22516629/calc_case_description_train_set.csv?version=1&modificationDate=1506796349666&api=v2
      calc_test: https://wiki.cancerimagingarchive.net/download/attachments/22516629/calc_case_description_test_set.csv?version=1&modificationDate=1506796343686&api=v2
      mass_train: https://wiki.cancerimagingarchive.net/download/attachments/22516629/mass_case_description_train_set.csv?version=1&modificationDate=1506796355038&api=v2
      mass_test: https://wiki.cancerimagingarchive.net/download/attachments/22516629/mass_case_description_test_set.csv?version=1&modificationDate=1506796343175&api=v2
    files:
      calc_train:
        stage: raw
        description: Calcification Training Set Description
        filepath: data/meta/0_raw/calc_case_description_train_set.csv
      calc_test:
        stage: raw
        description: Calciication Test Set Description
        filepath: data/meta/0_raw/calc_case_description_test_set.csv
      mass_train:
        stage: raw
        description: Mass Training Set Description
        filepath: data/meta/0_raw/mass_case_description_train_set.csv
      mass_test:
        stage: raw
        description: Mass Test Set Description
        filepath: data/meta/0_raw/mass_case_description_test_set.csv
      series:
        stage: raw
        description: Series Description
        filepath: data/meta/0_raw/metadata.csv


  images:
    source: CBIS-DDSM-All-doiJNLP-zzWs5zfZ.tcia
    destination: data/image/0_raw/

models: models/
