#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Deep Learning for Breast Cancer Detection                                           #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config.yml                                                                         #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/BreastCancerDetection                              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 21st 2023 07:46:07 pm                                              #
# Modified   : Saturday December 30th 2023 05:07:24 pm                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
data:
  base: data/
  image:
    raw: data/image/0_raw/
    exp: data/image/1_exp/
    final: data/image/2_final/
  meta:
    raw: data/meta/0_raw/
    unbox: data/meta/1_unbox/
    final: data/meta/2_final/


models: models/
