wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1699221805.757091
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 2
      - 23
      - 34
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
