#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Deep Learning for Breast Cancer Detection                                           #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /bcd/preprocess/config.yml                                                          #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/BreastCancerDetection                              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 21st 2023 05:07:18 pm                                              #
# Modified   : Saturday October 21st 2023 05:14:02 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
convert_png:
  source_dir: "data/image/0_raw"
  dest_dir: "data/image/1_png"
  dicom_meta_filepath: "data/meta/2_clean/dicom.csv"
  image_meta_filepath: "data/meta/2_clean/images.csv"
  n_images: 100
